name: Deployement

on:
  push:
    branches:
      - main

jobs:
  build:
    name: "Build the docker image"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout the code"
        uses: actions/checkout@v3
      - name: "Loging to Docker Hub"
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: "Build Docker image"
        uses: docker/build-push-action@v6
        with:
          context: .
          tags: ${{vars.DOCKER_IMAGE_TAG}}
          push: true

      - name: deploying
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}} 
            docker image pull ${{vars.DOCKER_IMAGE_TAG}}:latest
            docker container stop gt-action-demo
            docker container rm gt-action-demo
            docker container run -d --name gt-action-demo -p 80:5000 ${{vars.DOCKER_IMAGE_TAG}}
            docker logout
